name: CI - build,test affected projects on Pr+Merge
'on':
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: movies
        run: npx nx run movies:build

      - name: firebase-function
        run: npx nx run firebase-function:build

      - name: ng-universal-express
        run: npx nx run ng-universal-express:build

      - name: cloudflare-worker
        run: npx nx run cloudflare-worker:build



