name: Deploy - deploy affected projects
'on':
  pull_request:

jobs:
  delpoy:
    runs-on: ubuntu-latest
    steps:
      # needed for all cases
      - if: github.event_name == 'push' && github.ref_name == 'main'
        uses: actions/checkout@v3
      # needed for nx affected command
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # needed for nx affected command
      - if: github.event_name == 'pull_request'
        run: git fetch --no-tags --depth=1 origin $BASE_BRANCH

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: deploy affected projects
        id: deployStep
        run: |
          npm run nx affected --targets=deploy | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*" | echo"deployurl=%B" >> "$GITHUB_OUTPUT"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: echo outputs
        run: echo ${{steps.deployStep.outputs}}
