name: Deploy to GitHub README.md on Merge
on:
  push:
    branches:
      - main
jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Production build ( client + bundle stats )
        run: npm run nx run docs:build

      - name: Update main readme file
        uses: EndBug/add-and-commit@v7
        with:
          author_name: push-based.io
          author_email: opensource@push-based.io
          message: 'Update main readme file'
          add: '*'
