name: E2E NG Universal Express on PR
'on':
jobs:
  build_and_ng-universal-express:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Production build for static file hosting (client + prerender)
        run: npm run nx prerender ng-universal-express

      - name: Test ng-universal-express
        id: firebase-preview-channel-hosting
        uses: push-based/user-flow-gh-action@v0.4.0
        with:
          commentId: ng-universal-express
          verbose: on
          rcPath: projects/ng-universal-express/.user-flowrc.json
          outPath: dist/user-flow/ng-universal-express
