# This file executes @push-based/user-flow against the served SSR version of the current PR
name: user-flow-ci
on:
  pull_request:
jobs:
  user-flow-integrated-in-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci -f
      - name: Executing user-flow CLI
        uses: push-based/user-flow-gh-action@v0.1.2
        with:
          verbose: 'on'
          rcPath: ./projects/movies-user-flows/.user-flowrc.ci-csr.json
